name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/69 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Memer Action
      id: selftest

      uses: Bhupesh-V/memer-action@master
      with:
        filter: "new"
    - name: Check Memer Action Outputs
      run: |
        echo "${{ steps.selftest.outputs.meme }}"
        echo "${{ steps.selftest.outputs.title }}"
        echo "${{ steps.selftest.outputs.source }}"
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update README
      run: |-
        python build_readme.py "${{ steps.selftest.outputs.meme }}" "${{ steps.selftest.outputs.title }}" "${{ steps.selftest.outputs.source }}"
        cat README.md
    - name: Commit & Push
      run: |-
        git diff
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git add -A
        git commit -m "🤖 Automated Commit - add new meme"
        git push
