name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/69 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Memer Action
      id: meme

      uses: Bhupesh-V/memer-action@master
      with:
        filter: "new"
    - name: Check Memer Action Outputs
      run: |
        echo "${{ steps.meme.outputs.meme }}"
        echo "${{ steps.meme.outputs.title }}"
        echo "${{ steps.meme.outputs.source }}"
    - name: Update README
      run: |-
        python build_readme.py "${{ steps.selftest.outputs.meme }}" "${{ steps.selftest.outputs.title }}" "${{ steps.selftest.outputs.source }}"
    - name: Commit & Push
      run: |-
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git add -A
        git diff-index --quiet HEAD || git commit -m '🤖 Automated Commit - add new meme'
        git push
