name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Memer Action
      id: meme

      uses: Bhupesh-V/memer-action@master
      with:
        filter: "new"
    - name: Check Memer Action Outputs
      run: |
        echo "${{ steps.meme.outputs.meme }}"
        echo "${{ steps.meme.outputs.title }}"
        echo "${{ steps.meme.outputs.source }}"
    - name: Update README
      run: |-
        python build_readme.py "${{ steps.meme.outputs.meme }}" "${{ steps.meme.outputs.title }}" "${{ steps.meme.outputs.source }}"
    - name: Push new README.md
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
